### PR TITLE
win manifest paths

### PR DESCRIPTION
**Pull request by Bludator**
* Fixed replacing win paths. (There is used `Map` instead of array)
* By default all resources are *not* entries, except WebAccessibleResources
  * So it not separates files into folders and uses hash names in output

### CODE REVIEW

**Comment by kevincharm** [comment]
Hey @Bludator, thanks for the PR! I'll have a proper look sometime this week when I have a minute... are you able to rebase this to current master and target this PR to master instead?

**Comment by Bludator** [comment]
Ok,

...The tests are not passing due to the hashes in file names. :frowning:

**Comment by jrd-rocks** [comment]
This fix is not working for me. It seems there is some post-processinh going on.

To figure out wth is going on I tried to replace the rewrite function with
```const _replaceBundleNames = this.replaceBundleNames
        this.replaceBundleNames = bundleNameMap => {
            let newMap = new Map()
            for (const [name, map] of bundleNameMap) {
                console.log(`${name} ${map} -> ${upath.toUnix(map)}`)
                newMap.set(name, `h/h/${upath.toUnix(map)}`)
            }
            _replaceBundleNames.call(this, newMap)
        }```

and while the paths get replaced with `h\h\icons\icon16.png` the slashes are wrong again.

**Comment by xymopen** [comment]
Had the same issue but came up with another solution. We don't have to add a dep just for replacing the seperator! :P

```patch
From 5b09b6a0b645f5dfcc59b9a1c85eebf2501fb5ca Mon Sep 17 00:00:00 2001
From: xymopen <xuyiming.open@outlook.com>
Date: Tue, 16 Apr 2019 02:05:30 +0800
Subject: [PATCH] Fix bug when replacing bundle names on Windows

---
 src/ManifestAsset.js | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/src/ManifestAsset.js b/src/ManifestAsset.js
index 116bb45..88acd95 100644
--- a/src/ManifestAsset.js
+++ b/src/ManifestAsset.js
@@ -3,6 +3,7 @@ const glob = require('fast-glob')
 const Asset = require('parcel-bundler/src/Asset')
 const JSONAsset = require('parcel-bundler/src/assets/JSONAsset')
 const fs = require('@parcel/fs')
+const Path = require('path')
 
 /**
  * A shared asset that handles:
@@ -292,6 +293,14 @@ class ManifestAsset extends Asset {
 
         return this.contents
     }
+
+    replaceBundleNames(bundleNameMap) {
+        for (const [name, map] of bundleNameMap) {
+            bundleNameMap.set(name, Path.posix.join(...map.split(Path.sep)));
+        }
+
+        return super.replaceBundleNames( bundleNameMap );
+    }
 }
 
 module.exports = ManifestAsset
-- 
2.16.3.windows.1
```

**Comment by kevincharm** [comment]
Fixed in 1.6.0

**Pull request closed without merging**
