### PR TITLE
add options pages support

### PR DESCRIPTION
**Pull request by reosablo**
This plugin is just I wanted! I appreciate it!
Anyway, there is one lacking feature for me; options pages.

[https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Options_pages]

Please consider to process `options_ui` key and `options_page` key in `manifest.json` for WebExtension.

note: `options_page` is a [deprecated key](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json#Browser_compatibility).

### CODE REVIEW

**Comment by reosablo** [comment]
Thanks for reviewing!
I could't assume what way to add another test for `options_page` you like, so I hope you to do it to keep the project clean.

This patch works fine for me but there's a little mistake, sorry.
I forgot to receive the returned value from `this.processSingleDependency()`, so I will fix it before merging.

**Comment by reosablo** [comment]
I confirmed that this fix works fine for both `options_ui` and `options_page` in my own WebExtension project.
`manifest.json` output was the same in my case.

**Comment by kevincharm** [comment]
Oops, good catch!

**Comment by reosablo** [comment]
I'm happy you like it.
Thanks for reviewing again!

**Comment by kevincharm** [comment]
Will release in the morning. Cheers! :)

**Comment by reosablo** [comment]
Good!
Now I can update my `package.json` dependency.
Thank you very much!

**Pull request merged**
